# Generated by Django 4.0.4 on 2022-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_material_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='проба',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
