# Generated by Django 4.0.4 on 2022-06-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_проба'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='проба',
        ),
    ]
