# Generated by Django 4.0.4 on 2022-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_проба'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='material',
            new_name='collection_material',
        ),
    ]
