# Generated by Django 4.0.4 on 2022-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0007_alter_edumaterial_like'),
        ('users', '0006_rename_material_profile_collection_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='methodical_material.edumaterial'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collection_material',
            field=models.ManyToManyField(related_name='collection', to='methodical_material.edumaterial'),
        ),
    ]
