# Generated by Django 4.0.4 on 2022-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_comment_edu_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення'),
        ),
    ]
