# Generated by Django 4.0.4 on 2022-05-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='0075FF', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='EduСategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('type_category', models.CharField(choices=[('урок', 'урок'), ('---', '---')], default='---', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EduMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='edu_material')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('link_download', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodical_material.color')),
                ('edu_сategory', models.ManyToManyField(to='methodical_material.eduсategory')),
            ],
        ),
    ]
