# Generated by Django 4.0.4 on 2022-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0003_alter_edumaterial_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduсategory',
            name='long_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
