# Generated by Django 4.0.4 on 2022-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0004_eduсategory_long_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduсategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
