# Generated by Django 4.0.4 on 2022-05-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0006_edumaterial_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumaterial',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
