# Generated by Django 4.0.4 on 2022-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0008_alter_color_color_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edumaterial',
            name='count_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
