# Generated by Django 4.0.4 on 2022-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodical_material', '0009_edumaterial_count_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumaterial',
            name='count_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='к-ть коментарів'),
        ),
    ]
