# Generated by Django 4.0.4 on 2022-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='img',
            field=models.ImageField(upload_to='main_slider', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='text',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
    ]
