# Generated by Django 4.0.4 on 2022-05-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='img_position',
            field=models.CharField(choices=[('left', 'LEFT'), ('RIGHT', 'RIGHT')], default='left', max_length=10),
        ),
    ]
