# Generated by Django 4.0.4 on 2022-05-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_laboratory_img_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='products')),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('for_age', models.CharField(blank=True, max_length=20, null=True)),
                ('link_offsite', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.laboratory')),
            ],
        ),
    ]
