# Generated by Django 4.0.4 on 2022-06-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_product_link_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='background_color',
            field=models.CharField(help_text='Значення даного поля має бути записане в 16-й системі, #(решітку) прописувати не варто. Приклад: ff00ee', max_length=20, verbose_name='колір фону'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='img',
            field=models.ImageField(upload_to='labs', verbose_name='зображення'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='img_position',
            field=models.CharField(choices=[('left', 'ліворуч'), ('right', 'праворуч')], default='left', max_length=10, verbose_name='Розміщення'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='number_of_lab',
            field=models.PositiveSmallIntegerField(help_text='Для кожногї лабораторії номер має бути унікальний, показ лаболаторій відбувається за зростанням даного номеру.', verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Мається на увазі кількість працюючих наборів. Приклад: 5', null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Дане поле розуміє HTML та використовується для відображення вмісту модального вікна при натисканні на набір', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_age',
            field=models.CharField(blank=True, help_text='Приклад: від 4 до 12 років.', max_length=20, null=True, verbose_name='Допустимий вік'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.laboratory', verbose_name='Лоболаторія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_offsite',
            field=models.CharField(blank=True, help_text='посилання без врахування протоколу. Приклад: matatalab.com/en', max_length=255, null=True, verbose_name='Посилання на офіційний сайт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=10, verbose_name='Протокол офіційного сайту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_products',
            field=models.PositiveSmallIntegerField(help_text='Для кожного набору лобораторії номер має бути унікальний, показ наборів відбувається за зростанням даного номеру.', verbose_name='номер'),
        ),
    ]
