# Generated by Django 4.0.4 on 2022-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
