# Generated by Django 4.0.4 on 2022-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='pages', verbose_name='зображення'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_code',
            field=models.TextField(help_text='Контент який буде вставлений між HEADER та FOOTER', verbose_name='HTML код сторінки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.SlugField(help_text='Посилання не додається автоматично до меню. Приклад: mobile_lab', verbose_name='посилання'),
        ),
    ]
