# Generated by Django 4.0.4 on 2022-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardofmainslider',
            name='path_img',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
