# Generated by Django 4.0.4 on 2022-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_moduleofcourses_img_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img_position',
            field=models.CharField(choices=[('left', 'LEFT'), ('RIGHT', 'RIGHT')], default='left', max_length=10),
        ),
    ]
