# Generated by Django 4.0.4 on 2022-05-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_img_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='img_position',
        ),
    ]
