# Generated by Django 4.0.4 on 2022-05-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', "0005_rename_name_courses_ім'я"),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name="ім'я",
            new_name='name',
        ),
    ]
