# Generated by Django 4.0.4 on 2022-06-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', "0006_rename_ім'я_courses_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='age_of_student',
            field=models.CharField(help_text='Приклад: 9-10 років', max_length=50, verbose_name='вік учнів'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='background_color',
            field=models.CharField(help_text='Значення даного поля має бути записане в 16-й системі, #(решітку) прописувати не варто. Приклад: ff00ee', max_length=6, verbose_name='Колір фону'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='img_course',
            field=models.ImageField(upload_to='courses', verbose_name='Зодраження'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='max_count_of_students',
            field=models.CharField(help_text='Максимальна кількість яка може навчатись на цьому курсі. Приклад: 8 учнів', max_length=50, verbose_name='максимальна кількість учнів'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='number_of_courses',
            field=models.PositiveSmallIntegerField(help_text='\n                Для кожного курсу номер має бути унікальний,\n                 показ курсів відбувається за зростанням даного номеру.\n            ', verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='moduleofcourses',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='moduleofcourses',
            name='description',
            field=models.TextField(help_text='Кожна нова тема має бути введена з нового рядка', verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='moduleofcourses',
            name='img_module',
            field=models.ImageField(upload_to='modules', verbose_name='зображення'),
        ),
        migrations.AlterField(
            model_name='moduleofcourses',
            name='name',
            field=models.CharField(max_length=200, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='moduleofcourses',
            name='number_of_module',
            field=models.PositiveSmallIntegerField(help_text='Для кожного модуля в курсі номер має бути унікальний, показ модулів відбувається за зростанням даного номеру.', verbose_name='номер'),
        ),
    ]
